name: Build app and deploy to Tencent
on:
  #监听push操作
  push:
    branches:
      - master

jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 使用别人的action
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      # 步骤名称
      - name: Install dependencies and build
        # 步骤执行指令
        run: sh deploy.sh

      - name: Deploy to server via SCP
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: 'ssh scp ssh pipelines'
          LASTSSH: 'Doing something after copying'
        with:
          host: ${{ secrets.TENCENT_CLOUD_HOST }}
          user: ${{ secrets.TENCENT_CLOUD_USER }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          local: './vuepress/.vuepress/dist/*'
          remote: /root/wangtao/font-end-project/fe-js-ts