name: Build app and deploy to Tencent
on:
  #监听push操作
  push:
    branches:
      - master

jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 使用别人的action
      - uses: actions/checkout@v4
      
      # 步骤名称
      - name: Install dependencies and build
        # 步骤执行指令
        run: sh deploy.sh

      - name: Debug - List build files
        run: |
          echo "Checking if build files exist:"
          ls -la ./vuepress/.vuepress/dist/ || echo "Build directory not found"
          echo "Current working directory:"
          pwd
          echo "Directory structure:"
          find . -name "dist" -type d
          echo "Contents of vuepress/.vuepress/dist/:"
          ls -la ./vuepress/.vuepress/dist/ || echo "No dist directory found"

      - name: Verify build output
        run: |
          if [ ! -d "./vuepress/.vuepress/dist" ]; then
            echo "ERROR: Build directory does not exist!"
            exit 1
          fi
          if [ ! -f "./vuepress/.vuepress/dist/index.html" ]; then
            echo "ERROR: index.html not found in build output!"
            exit 1
          fi
          echo "Build verification passed!"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TENCENT_CLOUD_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.TENCENT_CLOUD_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          scp -r ./vuepress/.vuepress/dist/* ${{ secrets.TENCENT_CLOUD_USER }}@${{ secrets.TENCENT_CLOUD_HOST }}:/root/wangtao/font-end-project/fe-js-ts/
