name: Build app and deploy to Tencent
on:
  #监听push操作
  push:
    branches:
      # mian分支，你也可以改成其他分支
      - master

jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 使用别人的action
      - uses: actions/checkout@v2
      # 步骤名称
      - name: yarn & build
        # 步骤执行指令
        run: |
          sh deploy.sh
          echo "dist 目录内容如下："
          ls -al ./vuepress/.vuepress/dist
      #- name: yarn build
      #run: yarn build
      # 命名这个任务为发布Deploy
      - name: Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.USER_HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASS }}
          source: "./vuepress/.vuepress/dist"
          target: "/root/wangtao/font-end-project/FE-JS-TS"
          debug: true