name: Build app and deploy to Tencent
on:
  #监听push操作
  push:
    branches:
      # mian分支，你也可以改成其他分支
      - master

jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 使用别人的action
      - uses: actions/checkout@v2
      # 步骤名称
      - name: yarn&build
        # 步骤执行指令
        run: sh deploy.sh
      #- name: yarn build
      #run: yarn build
      # 命名这个任务为发布Deploy
      - name: Deploy
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.TENCENT_CLOUD_HOST }}
          user: ${{ secrets.TENCENT_CLOUD_USER }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          local: './vuepress/.vuepress/dist/*'
          remote: '/root/wangtao/font-end-project/fe-js-ts'
        env:
          WELCOME: 'ssh scp ssh pipelines'
          LASTSSH: 'Doing something after copying'
        