name: Build app and deploy to Tencent
on:
  #监听push操作
  push:
    branches:
      - master

jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 使用别人的action
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      # 步骤名称
      - name: Install dependencies and build
        # 步骤执行指令
        run: sh deploy.sh

      # 命名这个任务为发布Deploy
      - name: Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TENCENT_CLOUD_HOST }}
          username: ${{ secrets.TENCENT_CLOUD_USER }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          source: "./vuepress/.vuepress/dist/*"
          target: "/root/wangtao/font-end-project/fe-js-ts"